services:
  db:
    image: postgres:16
    container_name: tournament_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tournament_user
      POSTGRES_PASSWORD: tournament_pass
      POSTGRES_DB: tournament_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: